import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("/login", "routes/login.tsx"),
  route("/forgot-password", "routes/forgot-password.tsx"),
  route("/reset-password", "routes/reset-password.tsx"),
  route("/verify-email", "routes/verify-email.tsx"),
  route("/maintenance", "routes/maintenance.tsx"),
  route("/unauthorized", "routes/unauthorized.tsx"),
  route("/dashboard", "routes/dashboard.tsx"),
  route("/users", "routes/users.tsx"),
  route("/users-create", "routes/users-create.tsx"),
  route("/users/:id", "routes/users.$id.tsx"),
  route("/users/:id/edit", "routes/users.$id.edit.tsx"),
  route("/users/:id/roles", "routes/users.$id.roles.tsx"),
  route("/users/:id/permissions", "routes/users.$id.permissions.tsx"),
  route("/files", "routes/files.tsx"),
  route("/tags-create", "routes/tags-create.tsx"),
  route("/calendar-create", "routes/calendar-create.tsx"),
  route("/templates-create", "routes/templates-create.tsx"),
  route("/integrations-create", "routes/integrations-create.tsx"),
  route("/automation-create", "routes/automation-create.tsx"),
  route("/search", "routes/search.tsx"),
  route("/activities", "routes/activities.tsx"),
  // Feature routes
  route("/tasks", "routes/tasks.tsx"),
  route("/tasks-create", "routes/tasks-create.tsx"),
  route("/tasks/:id", "routes/tasks.$id.tsx"),
  route("/tasks/:id/edit", "routes/tasks.$id.edit.tsx"),
  route("/approvals", "routes/approvals.tsx"),
  route("/approvals-create", "routes/approvals-create.tsx"),
  route("/approvals/:id", "routes/approvals.$id.tsx"),
  route("/approvals/flows/:id", "routes/approflows.$id.view.tsx"),
  route("/approvals/flows/:id/edit", "routes/approflows.$id.edit.tsx"),
  route("/automation", "routes/automation.tsx"),
  route("/automation/:id", "routes/automation.$id.tsx"),
  route("/automation/:id/edit", "routes/automation.$id.edit.tsx"),
  route("/pubsub", "routes/pubsub.tsx"),
  route("/pubsub/streams/:streamId", "routes/pubsub.streams.$streamId.tsx"),
  route("/pubsub/groups/:groupId", "routes/pubsub.groups.$groupId.tsx"),
  route("/products", "routes/products.tsx"),
  route("/products-create", "routes/products-create.tsx"),
  route("/products/:id", "routes/products.$id.tsx"),
  route("/products/:id/edit", "routes/products.$id.edit.tsx"),
  route("/products/:id/variants", "routes/products.$id.variants.tsx"),
  route("/products/:id/barcodes", "routes/products.$id.barcodes.tsx"),
  // Config routes
  route("/config/theme", "routes/config.theme.tsx"),
  route("/config/modules", "routes/config.modules.tsx"),
  route("/config/general", "routes/config.general.tsx"),
  route("/config/roles", "routes/config.roles.tsx"),
  route("/config/notifications", "routes/config.notifications.tsx"),
  route("/config/integrations", "routes/config.integrations.tsx"),
  route("/config/quick-actions", "routes/config.quick-actions.tsx"),
  route("/config/import-export", "routes/config.import-export.tsx"),
  route("/config/audit", "routes/config.audit.tsx"),
  route("/config/files", "routes/config.files.tsx"),
  route("*", "routes/not-found.tsx"), // Catch-all para 404
] satisfies RouteConfig;
